### ISSUE TITLE
Expected end of text Error

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/USFM-Tools#1]
While processing https://github.com/unfoldingWord/ulb-en/blob/master/42-LUK-en-ULB.usfm:

```
python transform.py --target=usx --    usfmDir=/var/www/vhosts/api.unfoldingword.org/httpdocs/ulb/txt/1/ulb-en/ --builtDir=/tmp/ulb-usx --name=ULB
#### Starting Build.
#### Building for USX...

 LOADING ALL USFM FILES FROM /var/www/vhosts/api.unfoldingword.org/httpdocs/ulb/txt/1/ulb-en/
 Couldn't open .git
 Ignored LICENSE.usfm
 FINISHED LOADING

 (RUT)
Expected end of text (at char 126079), (line:2108, col:1)
u'\\id LUK unfoldingWord | Literal Bible\n\\ide UTF-8\n\\'
```

Ruth processed fine, but moving on to Luke appears to have broke something.  Reviewing the USX outputted file it appears that the USX does not have closing tags.  Is this not handling multiple files correctly?

Any thoughts?

**Comment by da1nerd** [comment]
it's because the text has some crazy broken format! :)
I believe it is a \\ somewhere in the source.

**Comment by da1nerd** [comment]
should be at (line:2108, col:1)

**Comment by jag3773** [comment]
Looks like it is https://github.com/unfoldingWord/ulb-en/blob/master/42-LUK-en-ULB.usfm#L2109.

**Comment by da1nerd** [comment]
correct.

**Comment by da1nerd** [comment]
there were a number of errors in the source that I had to fix in order to generate some test input for the app. This was the most obscure one though.

**Comment by jag3773** [comment]
OK, fixing the source files now...
