### ISSUE TITLE
Error Output Error

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/USFM-Tools#4]
While processing https://github.com/unfoldingWord/ulb-en/blob/master/01-GEN-en-ULB.usfm I get:
    (GEN)
    Error: After Genesis  6:32 - Unknown Token: \v

There are only 22 verses in Genesis 6.

**Comment by da1nerd** [comment]
The issue in the source is in 6:1
There's no space between the verse number and the comma.

The error message has it's own issues, I've passed this on to be resolved.
