### ISSUE TITLE
Add support for \qs

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/USFM-Tools#7]

**Comment by jag3773** [comment]
This issue was supposedly fixed in https://github.com/Door43/USFM-Tools/commit/01632fe211d23a14597e425651c9cde4f9bc466f but it does not support the correct end token: \qs\* .

**Comment by da1nerd** [comment]
on my radar thanks.

**Comment by jag3773** [comment]
This issue was moved to unfoldingWord-dev/Door43#342
